### ISSUE TITLE
Consistent fast click on mobile devices

### ISSUE THREAD

**Issue by jzaefferer** [jquery/standards#11]
Both iOS and Android make the generic click event seem unresponsive compared to their desktop counterparts. Whatever the motivation for that was, it makes building responsive web mobile apps a lot harder. 

While jQuery Mobile offers a solution for this issue (https://github.com/jquery/jquery-mobile/blob/master/js/jquery.mobile.vmouse.js), its a pretty complex implementation and very hard to apply outside the context of jQuery Mobile itself.

Obviously an incomplete description, but I hope to at least start a discussion around this.

**Comment by leobalter** [comment]
I've got a feedback from @arschmitz on irc and this seems to be solved now with touch-action css / pointer-events.

Polyfill here: https://github.com/hammerjs/hammer-time
