### ISSUE TITLE
A blacklist (not a whitelist) should define whether URL schemes are available for registration

### ISSUE THREAD

**Issue by Mithgol** [jquery/standards#12]
## Problem

[The current spec](http://www.whatwg.org/specs/web-apps/current-work/multipage/timers.html#custom-handlers "WhatWG HTML5, section 7.5.1.2: Custom scheme and content handlers") says:

> If the `registerProtocolHandler()` method is invoked with a scheme that is neither a whitelisted scheme nor a scheme whose value starts with the substring "`web+`" and otherwise contains only characters in the range U+0061 LATIN SMALL LETTER A to U+007A LATIN SMALL LETTER Z, the user agent must throw a `SecurityError` exception.

> The following schemes are the whitelisted schemes:

> + `irc`
> + `mailto`
> + `mms`
> + `news`
> + `nntp`
> + `sms`
> + `smsto`
> + `tel`
> + `urn`
> + `webcal`

> This list can be changed. If there are schemes that should be added, please send feedback.

**Whitelisted,** huh?

This is terrifying.

[In Wikipedia](http://en.wikipedia.org/wiki/URI_scheme#Official_IANA-registered_schemes "URI scheme") there is a list of — how many? — over a hundred official and unofficial schemes.

And that's precisely because none of them had to be *standartized* before use.

## Example

Now imagine that you have an idea of some Web application with a brand new URL scheme — such as `pay-to-github:username?amount` (compare it with the existing `skype:username?sendfile`).

Unfortunately, you cannot start seriously coding your application (as a Web application) for the next **ten** years, because your scheme has to make its way to the WhatWG whitelist and **only then** (according to the spec) to the separate whitelists inside of several browser versions. (IE6 is **ten** years old and still in use. Guess when some IE11, which does not support your scheme currently, will grow old enough to die?…)

Well, you may implement your URI scheme instantly — but only in standalone applications for the required platforms. Not for the wide cross-platform Web. At least not for the next ten years.

## Solution

A **blacklist** of dangerous schemes (schemes to be never redefined by Web applications) should be enough to ensure security. Otherwise the innovation would suffer.

**Comment by KrzysiekJ** [comment]
I’ve raised [that issue on the WHATWG mailing list](http://lists.w3.org/Archives/Public/public-whatwg-archive/2015Mar/0011.html).

**Comment by Mithgol** [comment]
Thanks.

**Comment by leobalter** [comment]
The discussion on this seems stalled for more than a year. Let's re-open this when we have any updates.
