### ISSUE TITLE
Safe names for custom events

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/standards#17]
There are a lot of developers using custom events in their code. Right now there is no way to be sure that your custom event names will be safe to use in the future as more native events get added.

## Specific Suggestions

* Create a prefix similar to `data-` attributes.
* Choose at least one character that will never appear in a native event so developers can include this somewhere in their custom event names. The form `foo:bar` seems to be somewhat popular.

**Comment by leobalter** [comment]
I'm assuming this is solved on the [CustomEvents api](https://w3c.github.io/uievents/#extending-events-Custom_Events). Please re-open if not.
