### ISSUE TITLE
Standardize `event.which` for MouseEvent

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/standards#18]
Browsers implement `event.which` for mouse events, and many users rely on it, but it's not defined in DOM Events. There is a standard for `event.button` and `event.buttons`, but according to jQuery's source it seems like at least one browser treats `event.button` as `event.buttons`.

**Comment by leobalter** [comment]
This is being tracked at https://github.com/w3c/uievents/issues/35

It seems this is becoming part of the legacy UIEvent interface. https://w3c.github.io/uievents/#dom-keyboardevent-which

@scottgonzalez can we close this or do you prefer waiting that uievents issue to be done?

**Comment by scottgonzalez** [comment]
I think ultimately we'll say we don't care about Mouse Events and just say this is solved with Pointer Events. So I'm ok with closing this since `button` and `buttons` should be correct in the new implementations.
