### ISSUE TITLE
Available selectors don’t meet developer needs

### ISSUE THREAD

**Issue by paulirish** [jquery/standards#3]
jQuery created a lot of sugar selectors that make finding relevant elements easier. It is now recommending against using many of them as they take a slow path and cannot leverage `querySelectorAll`. _Selectors Level 4_ should capture the selectors most used by jQuery developers.

## Action Items
* Identify what selectors in jQuery are in use and are currently not captured in _Selectors Level 4_

## References

http://dev.w3.org/csswg/selectors4/

**Comment by leobalter** [comment]
I assume the current [selectors4](https://drafts.csswg.org/selectors-4/) already covers this. Please re-open if necessary.
