### ISSUE TITLE
querySelectorAll is Often Surprisingly Slow

### ISSUE THREAD

**Issue by paulirish** [jquery/standards#4]
In many cases, querySelectorAll is slower than the counterpart DOM method for simple selectors. For instance, querySelectorAll(‘tagName’) is slower than getElementsByTagName(‘tagName’).

## Specific Issues

* querySelectorAll is slower than the lower-level DOM methods
  * querySelectorAll(tag) is slower than getElementsByTagName
  * querySelectorAll(class) is slower than getElementsByClassName
  * querySelectorAll(id) is slower than getElementById
* Action Items:
  * Do benchmarking on all browsers
  * File individual tickets with browser vendors for each instance in which querySelectorAll is slower than the lower-level DOM method
  * Make sure that the same mistake is not repeated with queryScopedSelector
     * Note: Why can we not just fix querySelectorAll? Are there cases where web authors are relying on the non-scoped behavior?
* External Contact: Browser vendors

## References

http://www.w3.org/TR/selectors-api/
http://www.w3.org/TR/selectors-api2/ 

## Conversation

http://lists.w3.org/Archives/Public/public-webapps/2011OctDec/0277.html

**Comment by leobalter** [comment]
I don't have the data from jsperf available anymore, but after some crude tests I made it seems the querySelectorAll is reasonably fast compared to getElementsByTagName, but the same results change drastically if I try the same checks manually on a console (FF, Safari, and Chrome) I can see a drastic change on querySelectorAll, probably happening by handling the NodeList return.

> File individual tickets with browser vendors for each instance in which querySelectorAll is slower than the lower-level DOM method

I guess this is already done, right?

We may re-open this If we have any further action to be done.
