### ISSUE TITLE
getElementsFromPoint

### ISSUE THREAD

**Issue by justinbmeyer** [jquery/standards#6]
Similar to:

https://developer.mozilla.org/En/DOM:document.elementFromPoint

There should be a getElementsFromPoint which will get all elements under a specific point.  This will make drag-drop type code much much easer (without needing to hide the dragging element).

This was echoed in some quirksmode blog post which I can no longer find.

**Comment by paulirish** [comment]
Done!

https://twitter.com/ChromiumDev/status/576081837165912064

part of CSSOM spec. now shipping in Chrome.

**Comment by leobalter** [comment]
Closing as I believe this is solved. Please re-open if not.
